# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e73f6f2772b8b7fd690f282efe85c11158be6e836b3c9820d0dadb310dc55887422719d9ec80c2fea96593dbab5048f84673c9ce2c2960e0e2460891ee65154

test:
  secret_key_base: 4e83918e8d7da93459635d126904bf50ad9f6e5d15407b211aed49b28a05428e92636b02390f6433ec300f16965b42150932f304f83234f0201f2428cd0773c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
